In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [36]:
with open ("C:\\Users\\Ravi Nadageri\\Desktop\\Py_Practice _file\\UNZIP_FOR_NOTEBOOKS_FINAL\\DATA\\One.txt", 'r') as a:
    data = a.read()

In [37]:
data

'This is a story about dogs\nour canine pets\nDogs are furry animals\n'

In [39]:
data.lower().split()

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [40]:
with open("C:\\Users\\Ravi Nadageri\\Desktop\\Py_Practice _file\\UNZIP_FOR_NOTEBOOKS_FINAL\\DATA\\One.txt") as mytext:
    word_one = mytext.read().lower().split()
    uniq_one = set(word_one)

In [41]:
uniq_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [42]:
with open("C:\\Users\\Ravi Nadageri\\Desktop\\Py_Practice _file\\UNZIP_FOR_NOTEBOOKS_FINAL\\DATA\\Two.txt") as mytext:
    word_two = mytext.read().lower().split()
    uniq_two = set(word_two)

In [43]:
uniq_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [44]:
all_uni_words = set()
all_uni_words.update(uniq_one)

In [ ]:
all_uni_words

In [45]:
all_uni_words.update(uniq_two)

In [46]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [47]:
full_vocablewords = dict()
i = 0

for word in all_uni_words:
    full_vocablewords[word] = i
    i = i + 1

In [48]:
full_vocablewords

{'sport': 0,
 'is': 1,
 'animals': 2,
 'this': 3,
 'pets': 4,
 'water': 5,
 'catching': 6,
 'surfing': 7,
 'dogs': 8,
 'canine': 9,
 'popular': 10,
 'a': 11,
 'story': 12,
 'furry': 13,
 'waves': 14,
 'fun': 15,
 'about': 16,
 'our': 17,
 'are': 18}

In [49]:
one_freq = [0]*len(full_vocablewords)
two_freq = [0]*len(full_vocablewords)

all_words = ['']*len(full_vocablewords)

In [50]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [51]:
with open("C:\\Users\\Ravi Nadageri\\Desktop\\Py_Practice _file\\UNZIP_FOR_NOTEBOOKS_FINAL\\DATA\\One.txt") as f:
    one_text = f.read().lower().split()
one_text

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

Now we have to count the the word in the one_text as how many counts for each

In [52]:
for word in one_text:
    word_ind = full_vocablewords[word]
    one_freq[word_ind] += 1

In [53]:
one_freq

[0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1]

In [54]:
with open("C:\\Users\\Ravi Nadageri\\Desktop\\Py_Practice _file\\UNZIP_FOR_NOTEBOOKS_FINAL\\DATA\\Two.txt") as f:
    two_text = f.read().lower().split()
two_text


['this',
 'story',
 'is',
 'about',
 'surfing',
 'catching',
 'waves',
 'is',
 'fun',
 'surfing',
 'is',
 'a',
 'popular',
 'water',
 'sport']

In [55]:
for word in two_text:
    word_ind = full_vocablewords[word]
    two_freq[word_ind] += 1
two_freq

[1, 3, 0, 1, 0, 1, 1, 2, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0]

In [56]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [57]:
for word in full_vocablewords:
    word_ind = full_vocablewords[word]
    all_words[word_ind] = word

In [58]:
all_words

['sport',
 'is',
 'animals',
 'this',
 'pets',
 'water',
 'catching',
 'surfing',
 'dogs',
 'canine',
 'popular',
 'a',
 'story',
 'furry',
 'waves',
 'fun',
 'about',
 'our',
 'are']

In [59]:
pd.DataFrame(data=[one_freq,two_freq],columns=all_words)

sport  is  animals  this  pets  water  catching  surfing  dogs  canine  \
0      0   1        1     1     1      0         0        0     2       1   
1      1   3        0     1     0      1         1        2     0       0   

   popular  a  story  furry  waves  fun  about  our  are  
0        0  1      1      1      0    0      1    1    1  
1        1  1      1      0      1    1      1    0    0

This is how the element frequecny present in both files or you can say the document 

In [60]:
text = ['This is a line',
        'This is a another line',
        'This is completely different line']

In [71]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [62]:
help(CountVectorizer)

Help on class CountVectorizer in module sklearn.feature_extraction.text:

class CountVectorizer(_VectorizerMixin, sklearn.base.BaseEstimator)
 |  CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)
 |  
 |  Convert a collection of text documents to a matrix of token counts.
 |  
 |  This implementation produces a sparse representation of the counts using
 |  scipy.sparse.csr_matrix.
 |  
 |  If you do not provide an a-priori dictionary and you do not use an analyzer
 |  that does some kind of feature selection then the number of features will
 |  be equal to the vocabulary size found by analyzing the data.
 |  
 |  Read more in the :ref:`User Guide <text_feature_extraction>`.
 |  
 |  Parameters
 |  -----

In [74]:
cv = CountVectorizer()

In [75]:
sparse_metrix = cv.fit_transform(text)

In [76]:
sparse_metrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 1, 1, 1]], dtype=int64)

In [77]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [68]:
cv = CountVectorizer(stop_words='english')

In [69]:
sparse_metrix = cv.fit_transform(text)
sparse_metrix.todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

It will remove the common english words

In [70]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [72]:
tfidf = TfidfTransformer()

In [73]:
sparse_metrix

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [79]:
result = tfidf.fit_transform(sparse_metrix)

In [80]:
result

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [83]:
result.todense()

matrix([[0.        , 0.        , 0.        , 0.57735027, 0.57735027,
         0.57735027],
        [0.69903033, 0.        , 0.        , 0.41285857, 0.41285857,
         0.41285857],
        [0.        , 0.57292883, 0.57292883, 0.338381  , 0.338381  ,
         0.338381  ]])

In [85]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [86]:
tv = TfidfVectorizer()

In [87]:
tv_result = tv.fit_transform(text)

In [90]:
tv_result.todense()

matrix([[0.        , 0.        , 0.        , 0.57735027, 0.57735027,
         0.57735027],
        [0.69903033, 0.        , 0.        , 0.41285857, 0.41285857,
         0.41285857],
        [0.        , 0.57292883, 0.57292883, 0.338381  , 0.338381  ,
         0.338381  ]])